/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Country;
import org.joda.time.LocalDate;


/**
 * Customer
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-08T09:39:43.225Z")
public class Customer   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("firstname")
  private String firstname = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("verified")
  private Integer verified = null;

  @SerializedName("birthday")
  private LocalDate birthday = null;

  @SerializedName("gender")
  private Integer gender = null;

  @SerializedName("address_1")
  private String address1 = null;

  @SerializedName("address_2")
  private String address2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("county")
  private String county = null;

  @SerializedName("postcode")
  private String postcode = null;

  @SerializedName("country_id")
  private Long countryId = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("last_dive")
  private LocalDate lastDive = null;

  @SerializedName("number_of_dives")
  private Integer numberOfDives = null;

  @SerializedName("chest_size")
  private String chestSize = null;

  @SerializedName("shoe_size")
  private String shoeSize = null;

  @SerializedName("height")
  private String height = null;

  @SerializedName("cylinder_size")
  private String cylinderSize = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("unsubscribed")
  private Boolean unsubscribed = null;

  @SerializedName("country")
  private Country country = null;

  public Customer id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Customer email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Customer firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

   /**
   * Get firstname
   * @return firstname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public Customer lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * Get lastname
   * @return lastname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public Customer verified(Integer verified) {
    this.verified = verified;
    return this;
  }

   /**
   * Get verified
   * @return verified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVerified() {
    return verified;
  }

  public void setVerified(Integer verified) {
    this.verified = verified;
  }

  public Customer birthday(LocalDate birthday) {
    this.birthday = birthday;
    return this;
  }

   /**
   * Get birthday
   * @return birthday
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getBirthday() {
    return birthday;
  }

  public void setBirthday(LocalDate birthday) {
    this.birthday = birthday;
  }

  public Customer gender(Integer gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGender() {
    return gender;
  }

  public void setGender(Integer gender) {
    this.gender = gender;
  }

  public Customer address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public Customer address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public Customer city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Customer county(String county) {
    this.county = county;
    return this;
  }

   /**
   * Get county
   * @return county
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCounty() {
    return county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public Customer postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public Customer countryId(Long countryId) {
    this.countryId = countryId;
    return this;
  }

   /**
   * Get countryId
   * @return countryId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCountryId() {
    return countryId;
  }

  public void setCountryId(Long countryId) {
    this.countryId = countryId;
  }

  public Customer phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Customer lastDive(LocalDate lastDive) {
    this.lastDive = lastDive;
    return this;
  }

   /**
   * Get lastDive
   * @return lastDive
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getLastDive() {
    return lastDive;
  }

  public void setLastDive(LocalDate lastDive) {
    this.lastDive = lastDive;
  }

  public Customer numberOfDives(Integer numberOfDives) {
    this.numberOfDives = numberOfDives;
    return this;
  }

   /**
   * Get numberOfDives
   * @return numberOfDives
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNumberOfDives() {
    return numberOfDives;
  }

  public void setNumberOfDives(Integer numberOfDives) {
    this.numberOfDives = numberOfDives;
  }

  public Customer chestSize(String chestSize) {
    this.chestSize = chestSize;
    return this;
  }

   /**
   * Get chestSize
   * @return chestSize
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChestSize() {
    return chestSize;
  }

  public void setChestSize(String chestSize) {
    this.chestSize = chestSize;
  }

  public Customer shoeSize(String shoeSize) {
    this.shoeSize = shoeSize;
    return this;
  }

   /**
   * Get shoeSize
   * @return shoeSize
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShoeSize() {
    return shoeSize;
  }

  public void setShoeSize(String shoeSize) {
    this.shoeSize = shoeSize;
  }

  public Customer height(String height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHeight() {
    return height;
  }

  public void setHeight(String height) {
    this.height = height;
  }

  public Customer cylinderSize(String cylinderSize) {
    this.cylinderSize = cylinderSize;
    return this;
  }

   /**
   * Get cylinderSize
   * @return cylinderSize
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCylinderSize() {
    return cylinderSize;
  }

  public void setCylinderSize(String cylinderSize) {
    this.cylinderSize = cylinderSize;
  }

  public Customer notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public Customer unsubscribed(Boolean unsubscribed) {
    this.unsubscribed = unsubscribed;
    return this;
  }

   /**
   * Get unsubscribed
   * @return unsubscribed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUnsubscribed() {
    return unsubscribed;
  }

  public void setUnsubscribed(Boolean unsubscribed) {
    this.unsubscribed = unsubscribed;
  }

  public Customer country(Country country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "")
  public Country getCountry() {
    return country;
  }

  public void setCountry(Country country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.id, customer.id) &&
        Objects.equals(this.email, customer.email) &&
        Objects.equals(this.firstname, customer.firstname) &&
        Objects.equals(this.lastname, customer.lastname) &&
        Objects.equals(this.verified, customer.verified) &&
        Objects.equals(this.birthday, customer.birthday) &&
        Objects.equals(this.gender, customer.gender) &&
        Objects.equals(this.address1, customer.address1) &&
        Objects.equals(this.address2, customer.address2) &&
        Objects.equals(this.city, customer.city) &&
        Objects.equals(this.county, customer.county) &&
        Objects.equals(this.postcode, customer.postcode) &&
        Objects.equals(this.countryId, customer.countryId) &&
        Objects.equals(this.phone, customer.phone) &&
        Objects.equals(this.lastDive, customer.lastDive) &&
        Objects.equals(this.numberOfDives, customer.numberOfDives) &&
        Objects.equals(this.chestSize, customer.chestSize) &&
        Objects.equals(this.shoeSize, customer.shoeSize) &&
        Objects.equals(this.height, customer.height) &&
        Objects.equals(this.cylinderSize, customer.cylinderSize) &&
        Objects.equals(this.notes, customer.notes) &&
        Objects.equals(this.unsubscribed, customer.unsubscribed) &&
        Objects.equals(this.country, customer.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, email, firstname, lastname, verified, birthday, gender, address1, address2, city, county, postcode, countryId, phone, lastDive, numberOfDives, chestSize, shoeSize, height, cylinderSize, notes, unsubscribed, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    county: ").append(toIndentedString(county)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    lastDive: ").append(toIndentedString(lastDive)).append("\n");
    sb.append("    numberOfDives: ").append(toIndentedString(numberOfDives)).append("\n");
    sb.append("    chestSize: ").append(toIndentedString(chestSize)).append("\n");
    sb.append("    shoeSize: ").append(toIndentedString(shoeSize)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    cylinderSize: ").append(toIndentedString(cylinderSize)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    unsubscribed: ").append(toIndentedString(unsubscribed)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

