/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Boat;
import io.swagger.client.model.Trip;
import org.joda.time.LocalDate;


/**
 * Session
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-08T09:39:43.225Z")
public class Session   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("trip")
  private Trip trip = null;

  @SerializedName("start")
  private LocalDate start = null;

  @SerializedName("boat")
  private Boat boat = null;

  @SerializedName("timetable_id")
  private Long timetableId = null;

  public Session id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Session trip(Trip trip) {
    this.trip = trip;
    return this;
  }

   /**
   * Get trip
   * @return trip
  **/
  @ApiModelProperty(example = "null", value = "")
  public Trip getTrip() {
    return trip;
  }

  public void setTrip(Trip trip) {
    this.trip = trip;
  }

  public Session start(LocalDate start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getStart() {
    return start;
  }

  public void setStart(LocalDate start) {
    this.start = start;
  }

  public Session boat(Boat boat) {
    this.boat = boat;
    return this;
  }

   /**
   * Get boat
   * @return boat
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boat getBoat() {
    return boat;
  }

  public void setBoat(Boat boat) {
    this.boat = boat;
  }

  public Session timetableId(Long timetableId) {
    this.timetableId = timetableId;
    return this;
  }

   /**
   * Get timetableId
   * @return timetableId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTimetableId() {
    return timetableId;
  }

  public void setTimetableId(Long timetableId) {
    this.timetableId = timetableId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Session session = (Session) o;
    return Objects.equals(this.id, session.id) &&
        Objects.equals(this.trip, session.trip) &&
        Objects.equals(this.start, session.start) &&
        Objects.equals(this.boat, session.boat) &&
        Objects.equals(this.timetableId, session.timetableId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, trip, start, boat, timetableId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Session {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    trip: ").append(toIndentedString(trip)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    boat: ").append(toIndentedString(boat)).append("\n");
    sb.append("    timetableId: ").append(toIndentedString(timetableId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

