/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse20023;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.InlineResponse20024;
import io.swagger.client.model.InlineResponse20025;
import io.swagger.client.model.InlineResponse20026;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyApi
 */
public class CompanyApiTest {

    private final CompanyApi api = new CompanyApi();

    
    /**
     * Attach a location to a company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachLocationsTest() throws ApiException {
        String name = null;
        String description = null;
        Float latitude = null;
        Float longitude = null;
        // InlineResponse20023 response = api.attachLocations(name, description, latitude, longitude);

        // TODO: test validations
    }
    
    /**
     * Retrieve the locations this Dive Centre uses
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationsTest() throws ApiException {
        String latitude = null;
        String longitude = null;
        Integer limit = null;
        // InlineResponse20024 response = api.getLocations(latitude, longitude, limit);

        // TODO: test validations
    }
    
    /**
     * Retrieve the pick up schedule for a date
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPickupScheduleTest() throws ApiException {
        String date = null;
        // InlineResponse20025 response = api.getPickupSchedule(date);

        // TODO: test validations
    }
    
    /**
     * Update the companies information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCompanyTest() throws ApiException {
        Long id = null;
        String contact = null;
        String description = null;
        String name = null;
        String address1 = null;
        String address2 = null;
        String city = null;
        String county = null;
        String postcode = null;
        Long countryId = null;
        Long currencyId = null;
        String businessPhone = null;
        String businessEmail = null;
        String vatNumber = null;
        String registrationNumber = null;
        String website = null;
        // InlineResponse20026 response = api.updateCompany(id, contact, description, name, address1, address2, city, county, postcode, countryId, currencyId, businessPhone, businessEmail, vatNumber, registrationNumber, website);

        // TODO: test validations
    }
    
}
