/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LocationApi
 */
public class LocationApiTest {

    private final LocationApi api = new LocationApi();

    
    /**
     * Attach a location to a company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachLocationTest() throws ApiException {
        Long locationId = null;
        // InlineResponse2003 response = api.attachLocation(locationId);

        // TODO: test validations
    }
    
    /**
     * Create a location
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createLocationTest() throws ApiException {
        String name = null;
        String description = null;
        Float latitude = null;
        Float longitude = null;
        List<Long> tags = null;
        // InlineResponse2003 response = api.createLocation(name, description, latitude, longitude, tags);

        // TODO: test validations
    }
    
    /**
     * Dettach a location to a company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void dettachLocationTest() throws ApiException {
        Long locationId = null;
        // InlineResponse2003 response = api.dettachLocation(locationId);

        // TODO: test validations
    }
    
    /**
     * Retrieve all locations associated with the company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllLocationsTest() throws ApiException {
        // InlineResponse2003 response = api.getAllLocations();

        // TODO: test validations
    }
    
    /**
     * Retrieve all tags associated to all locations
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationTagsTest() throws ApiException {
        // InlineResponse2003 response = api.getLocationTags();

        // TODO: test validations
    }
    
    /**
     * Update a location
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateLocationTest() throws ApiException {
        Long locationId = null;
        Long description = null;
        // InlineResponse2003 response = api.updateLocation(locationId, description);

        // TODO: test validations
    }
    
}
