/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse20032;
import io.swagger.client.model.ErrorModel;
import org.joda.time.LocalDate;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.InlineResponse20033;
import io.swagger.client.model.ModelPackage;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PackageApi
 */
public class PackageApiTest {

    private final PackageApi api = new PackageApi();

    
    /**
     * Create a new package
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPackageTest() throws ApiException {
        String name = null;
        String description = null;
        LocalDate availableFrom = null;
        LocalDate availableUntil = null;
        List<Long> tickets = null;
        List<Long> courses = null;
        List<Long> accommodations = null;
        List<Long> addons = null;
        List<Long> prices = null;
        // InlineResponse20032 response = api.createPackage(name, description, availableFrom, availableUntil, tickets, courses, accommodations, addons, prices);

        // TODO: test validations
    }
    
    /**
     * Delete a package by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePackageTest() throws ApiException {
        Long id = null;
        // InlineResponse2003 response = api.deletePackage(id);

        // TODO: test validations
    }
    
    /**
     * Update a package by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editPackageTest() throws ApiException {
        Long id = null;
        String name = null;
        String description = null;
        LocalDate availableFrom = null;
        LocalDate availableUntil = null;
        List<Long> tickets = null;
        List<Long> courses = null;
        List<Long> accommodations = null;
        List<Long> addons = null;
        List<Long> prices = null;
        // InlineResponse20033 response = api.editPackage(id, name, description, availableFrom, availableUntil, tickets, courses, accommodations, addons, prices);

        // TODO: test validations
    }
    
    /**
     * Retrieve all packages including any deleted models
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPackagesTest() throws ApiException {
        // List<ModelPackage> response = api.getAllPackages();

        // TODO: test validations
    }
    
    /**
     * Retrieve all packages including any deleted models
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllWithTrashedPackagesTest() throws ApiException {
        // List<ModelPackage> response = api.getAllWithTrashedPackages();

        // TODO: test validations
    }
    
    /**
     * Retrieve a package by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPackageTest() throws ApiException {
        Long id = null;
        // InlineResponse20032 response = api.getPackage(id);

        // TODO: test validations
    }
    
}
