/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2011;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.InlineResponse20035;
import org.joda.time.LocalDate;
import io.swagger.client.model.Payment;
import io.swagger.client.model.InlineResponse20034;
import io.swagger.client.model.InlineResponse20036;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentApi
 */
public class PaymentApiTest {

    private final PaymentApi api = new PaymentApi();

    
    /**
     * Create a new payment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPaymentTest() throws ApiException {
        Long bookingId = null;
        Long paymentgatewayId = null;
        Float amount = null;
        // InlineResponse2011 response = api.addPayment(bookingId, paymentgatewayId, amount);

        // TODO: test validations
    }
    
    /**
     * Retrieve all payments that match a filter
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void filterPaymentsTest() throws ApiException {
        LocalDate after = null;
        LocalDate before = null;
        // InlineResponse20035 response = api.filterPayments(after, before);

        // TODO: test validations
    }
    
    /**
     * Retrieve all payments made
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPaymentsTest() throws ApiException {
        // List<Payment> response = api.getAllPayments();

        // TODO: test validations
    }
    
    /**
     * Retrieve a payment by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentTest() throws ApiException {
        Long id = null;
        // InlineResponse20034 response = api.getPayment(id);

        // TODO: test validations
    }
    
    /**
     * Retrieve all the payment gateways
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentGatewaysTest() throws ApiException {
        // InlineResponse20036 response = api.getPaymentGateways();

        // TODO: test validations
    }
    
}
