/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.InlineResponse20046;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.InlineResponse20047;
import io.swagger.client.model.Trip;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TripApi
 */
public class TripApiTest {

    private final TripApi api = new TripApi();

    
    /**
     * Create a new trip
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTripTest() throws ApiException {
        String name = null;
        Float duration = null;
        List<Long> locations = null;
        List<Long> tags = null;
        String description = null;
        Boolean boatRequired = null;
        // InlineResponse20046 response = api.createTrip(name, duration, locations, tags, description, boatRequired);

        // TODO: test validations
    }
    
    /**
     * Delete a trip by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTripTest() throws ApiException {
        Long id = null;
        // InlineResponse2003 response = api.deleteTrip(id);

        // TODO: test validations
    }
    
    /**
     * Update a trip by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editTripTest() throws ApiException {
        Long id = null;
        String name = null;
        Float duration = null;
        List<Long> locations = null;
        List<Long> tags = null;
        String description = null;
        Boolean boatRequired = null;
        // InlineResponse20047 response = api.editTrip(id, name, duration, locations, tags, description, boatRequired);

        // TODO: test validations
    }
    
    /**
     * Retrieve all trips including any deleted models
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTripsTest() throws ApiException {
        // List<Trip> response = api.getAllTrips();

        // TODO: test validations
    }
    
    /**
     * Retrieve all trips including any deleted models
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllWithTrashedTripsTest() throws ApiException {
        // List<Trip> response = api.getAllWithTrashedTrips();

        // TODO: test validations
    }
    
    /**
     * Retrieve a trip by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tripGetTest() throws ApiException {
        Long id = null;
        // Trip response = api.tripGet(id);

        // TODO: test validations
    }
    
}
